# Generated by Django 3.0 on 2019-12-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=9)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('habitaciones', models.IntegerField()),
                ('disponibilidad', models.CharField(choices=[('SI', 'DISPOPNIBLE'), ('NO', 'NO DISPONIBLE')], default='SI', max_length=20)),
                ('jardin', models.CharField(choices=[('SI', 'CON JARDIN'), ('NO', 'SIN JARDIN')], default='NO', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='departameto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=9)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('habitaciones', models.IntegerField()),
                ('disponibilidad', models.CharField(choices=[('SI', 'DISPOPNIBLE'), ('NO', 'NO DISPONIBLE')], default='SI', max_length=20)),
                ('piso', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
